# Generated by Django 3.2.9 on 2024-09-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.DateTimeField(),
        ),
    ]
